# Generated by Django 3.2 on 2021-04-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('genre', models.IntegerField()),
                ('artist', models.URLField()),
                ('tracks', models.URLField()),
                ('myself', models.URLField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField()),
                ('artist', models.URLField()),
                ('album', models.URLField()),
                ('myself', models.URLField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.album')),
            ],
        ),
    ]
