# Generated by Django 3.2 on 2021-04-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_album_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='track',
            name='album_id',
            field=models.CharField(max_length=30),
        ),
    ]
